#ここをEC2のサーバー側で作ったMysqlのユーザー名、パスワード、ホスト名を書く
production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  
  producution:
  database: aws-event-sample-app_producution
